### ISSUE TITLE
Server address

### ISSUE THREAD

**Issue by TJay76** [hattabatatta/KodiLexa#1]
Two questions...

1. How many instances can Kodilexa work with? 

2. What do I put in the server address box on Kodi connector?

Other than that, everything else is simple!

**Comment by hattabatatta** [comment]
Hi there.

1) At the moment only one instance.

2) The address to reach your kodi from outside your network. A domain (with no-ip or dyndns for example) or an IP.

Regards

**Comment by hattabatatta** [comment]
The feature to control more than one instance is implemented
