### ISSUE TITLE
Website or email don't work

### ISSUE THREAD

**Issue by slack8182** [hattabatatta/KodiLexa#2]
I tried logging on to your site with no luck then I sent you an email and it said it couldn't be delivered. What do I do?

**Comment by hattabatatta** [comment]
Hey there!

The website is no longer working, since I took KodiLexa offline a few month ago ... the eMail account also.
I completely redesigned KodiLexa for some reasons ... and at the moment the redesign is only available in german.

**Comment by stderror** [comment]
Hi @hattabatatta 

Where is the german redesign available or how can I use it?
