### ISSUE TITLE
invite

### ISSUE THREAD

**Issue by fred959** [hattabatatta/KodiLexa#3]
fred911@gmail.com I won't ever bitch at ya and I'm not a dead-end user. Sorry you got all the BS on your first round. I'd be happy to make english documentation for the project. Running kodi on a firestick, haven't used windows [except in a virtual box] in 10 years only various flavors of debian or linux. I haven't coded since the DB3/Foxpro days but I'm by no means helpless. If you could use some beta guys or could use the platforms I use, let me know. Thanks again.. email is best..

**Comment by hattabatatta** [comment]
Thank you for your message. I´ll going to mail to the facts about the english version and I appreciate your offer to help ... but there is no need :)
